# Generated by Django 4.0.4 on 2022-05-16 14:54

from django.db import migrations, models
from django.utils import version

try:
    from django.db.models import JSONField
except ImportError:
    from django.contrib.postgres.fields import JSONField


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    if version.get_version() >= "3.2":
        auto_field_class = models.BigAutoField
    else:
        auto_field_class = models.AutoField

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    auto_field_class(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=64)),
                ("payload", JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
