# Generated by Django 4.0.4 on 2022-05-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jaiminho", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="encoder",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="function_signature",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="options",
            field=models.TextField(blank=True),
        ),
    ]
