# Generated by Django 4.0.4 on 2022-05-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jaiminho", "0002_event_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="encoder",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
