# Generated by Django 4.0.4 on 2022-07-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jaiminho", "0002_event_encoder_event_function_signature_event_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="action",
        ),
        migrations.RemoveField(
            model_name="event",
            name="encoder",
        ),
        migrations.RemoveField(
            model_name="event",
            name="function_signature",
        ),
        migrations.RemoveField(
            model_name="event",
            name="options",
        ),
        migrations.RemoveField(
            model_name="event",
            name="payload",
        ),
        migrations.RemoveField(
            model_name="event",
            name="type",
        ),
        migrations.AddField(
            model_name="event",
            name="function",
            field=models.BinaryField(max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="kwargs",
            field=models.BinaryField(max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="message",
            field=models.BinaryField(max_length=65535, null=True),
        ),
    ]
