# Generated by Django 4.0.6 on 2022-08-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jaiminho", "0003_remove_event_action_remove_event_encoder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="stream",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
