# Generated by Django 4.0.4 on 2022-05-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jaiminho", "0003_event_encoder"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="function_signature",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="encoder",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
