# Generated by Django 4.1.7 on 2024-11-01 14:40

from django.db import migrations, connection


class Migration(migrations.Migration):

    dependencies = [
        ("jaiminho", "0006_alter_event_id"),
    ]

    operations = []

    if connection.vendor == "postgresql":
        operations.append(
            migrations.RunSQL(
                "ALTER TABLE jaiminho_event ALTER COLUMN id TYPE BIGINT;",
            )
        )
    elif connection.vendor == "mysql":
        operations.append(
            migrations.RunSQL(
                "ALTER TABLE jaiminho_event MODIFY id BIGINT;",
            )
        )
