# Generated by Django 6.0.5 on 2026-05-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jaiminho", "0007_alter_event_id_to_bigint"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="signature",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
